package tasks

import (
	"encoding/json"
	"fmt"
)

const TypeIndexRepo = "repo:index"

// IndexRepoPayload is the payload sent when enqueuing a repo indexing task.
type IndexRepoPayload struct {
	RepoID      string `json:"repoId"`
	Owner       string `json:"owner"`
	Repo        string `json:"repo"`
	AccessToken string `json:"accessToken"`
}

// SetupGuide contains structured setup and configuration instructions.
type SetupGuide struct {
	Prerequisites string `json:"prerequisites"`
	Installation  string `json:"installation"`
	Configuration string `json:"configuration"`
	Running       string `json:"running"`
	Testing       string `json:"testing"`
}

// SystemOverview is the top-level repo summary generated by Claude.
type SystemOverview struct {
	Description    string     `json:"description"`
	Purpose        string     `json:"purpose"`
	KeyFeatures    []string   `json:"keyFeatures"`
	GettingStarted string     `json:"gettingStarted"`
	MainLanguage   string     `json:"mainLanguage"`
	RepoType       string     `json:"repoType"`
	SetupGuide     SetupGuide `json:"setupGuide"`
}

// ArchComponent represents a single architectural component.
type ArchComponent struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Path        string   `json:"path"`
	DependsOn   []string `json:"dependsOn"`
}

// ArchDiagram is a Mermaid diagram with a caption.
type ArchDiagram struct {
	Title   string `json:"title"`
	Type    string `json:"type"`
	Content string `json:"content"`
}

// Architecture describes the high-level architecture of the repo.
type Architecture struct {
	Description string          `json:"description"`
	Components  []ArchComponent `json:"components"`
	DataFlow    string          `json:"dataFlow"`
	Diagrams    []ArchDiagram   `json:"diagrams"`
}

// TechStack describes the technologies used in the repo.
type TechStack struct {
	Languages      []string `json:"languages"`
	Frameworks     []string `json:"frameworks"`
	Databases      []string `json:"databases"`
	Tools          []string `json:"tools"`
	Infrastructure []string `json:"infrastructure"`
}

// ModuleExport describes a key export from a module.
type ModuleExport struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

// ModuleAnalysis is the documentation for a single source code module/directory.
type ModuleAnalysis struct {
	ModuleName           string         `json:"moduleName"`
	ModulePath           string         `json:"modulePath"`
	Description          string         `json:"description"`
	KeyExports           []ModuleExport `json:"keyExports"`
	InternalDependencies []string       `json:"internalDependencies"`
	PublicAPI            []string       `json:"publicAPI"`
	SourceFiles          []string       `json:"sourceFiles"`
}

// EntryPoint describes a single entry point in the repo.
type EntryPoint struct {
	Name        string `json:"name"`
	Path        string `json:"path"`
	Description string `json:"description"`
	Type        string `json:"type"`
}

// EntryPoints groups all entry points by category.
type EntryPoints struct {
	Main   []EntryPoint `json:"main"`
	CLI    []EntryPoint `json:"cli"`
	API    []EntryPoint `json:"api"`
	Config []EntryPoint `json:"config"`
}

// UnmarshalJSON handles LLM responses where a field may be a string instead of
// an array of EntryPoint objects (e.g. "cli": "No CLI entry points").
func (ep *EntryPoints) UnmarshalJSON(data []byte) error {
	// Use a raw map so we can inspect each field's JSON type.
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return fmt.Errorf("unmarshaling EntryPoints: %w", err)
	}

	ep.Main = unmarshalEntryPointField(raw["main"])
	ep.CLI = unmarshalEntryPointField(raw["cli"])
	ep.API = unmarshalEntryPointField(raw["api"])
	ep.Config = unmarshalEntryPointField(raw["config"])
	return nil
}

// unmarshalEntryPointField tries to decode as []EntryPoint; if the LLM
// returned a bare string or other non-array type, it returns nil.
func unmarshalEntryPointField(data json.RawMessage) []EntryPoint {
	if len(data) == 0 {
		return nil
	}
	var entries []EntryPoint
	if err := json.Unmarshal(data, &entries); err == nil {
		return entries
	}
	// LLM returned something other than an array — skip gracefully.
	return nil
}

// KeyDependency is an important dependency with a description of its purpose.
type KeyDependency struct {
	Name    string `json:"name"`
	Purpose string `json:"purpose"`
}

// Dependencies describes the project's dependency landscape.
type Dependencies struct {
	Runtime []string        `json:"runtime"`
	Dev     []string        `json:"dev"`
	Key     []KeyDependency `json:"key"`
}

// SynthesisResult is the combined output from the synthesis LLM stage.
type SynthesisResult struct {
	Architecture Architecture `json:"architecture"`
	TechStack    TechStack    `json:"techStack"`
	EntryPoints  EntryPoints  `json:"entryPoints"`
	Dependencies Dependencies `json:"dependencies"`
}

// Documentation represents the full generated documentation for a repository.
type Documentation struct {
	SystemOverview SystemOverview   `json:"systemOverview"`
	Architecture   Architecture     `json:"architecture"`
	TechStack      TechStack        `json:"techStack"`
	KeyModules     []ModuleAnalysis `json:"keyModules"`
	EntryPoints    EntryPoints      `json:"entryPoints"`
	Dependencies   Dependencies     `json:"dependencies"`
	RepoContext    string           `json:"repoContext"`
}

// FileStructure holds parsed code structure for a single file.
type FileStructure struct {
	Path      string        `json:"path"`
	Language  string        `json:"language"`
	Imports   []string      `json:"imports"`
	Exports   []string      `json:"exports"`
	Functions []FunctionSig `json:"functions"`
	Classes   []ClassSig    `json:"classes"`
	Constants []string      `json:"constants"`
	TypeDefs  []string      `json:"typeDefs"`
}

// FunctionSig represents a function signature extracted by tree-sitter.
type FunctionSig struct {
	Name       string `json:"name"`
	Params     string `json:"params"`
	ReturnType string `json:"returnType"`
	IsExported bool   `json:"isExported"`
	DocComment string `json:"docComment"`
}

// ClassSig represents a class/struct signature extracted by tree-sitter.
type ClassSig struct {
	Name       string        `json:"name"`
	Methods    []FunctionSig `json:"methods"`
	Fields     []string      `json:"fields"`
	IsExported bool          `json:"isExported"`
}

// DirectoryChunk groups file structures by top-level directory for LLM processing.
type DirectoryChunk struct {
	DirPath       string          `json:"dirPath"`
	Files         []FileStructure `json:"files"`
	TokenEstimate int             `json:"tokenEstimate"`
}

// MarshalPayload encodes an IndexRepoPayload to JSON bytes.
func MarshalPayload(p IndexRepoPayload) ([]byte, error) {
	return json.Marshal(p)
}

// UnmarshalPayload decodes JSON bytes into an IndexRepoPayload.
func UnmarshalPayload(data []byte) (IndexRepoPayload, error) {
	var p IndexRepoPayload
	err := json.Unmarshal(data, &p)
	return p, err
}
